### ISSUE TITLE
Failed to get access to GAPartNet_All dataset

### ISSUE THREAD

**Issue by OolongQian** [PKU-EPIC/GAPartNet#12]
Dear haoran,

Firstly, I want to express my appreciation to your impressive work of GAPartNet. I am interested in reproducing your results. But I find that current link, leading to data in google drive, provides some data but not GAPartNet_All, which is required in reproducing your work. I would like to ask you for your help in having access to GAPartNet_All. I look forward to your response. 

Best regards, Sucheng Qian

**Comment by geng-haoran** [comment]
Yes, we currently provide all the source data and rendering code. Initially we provided all the data in the Peking University repo, but currently it is outdated and we have to move to google drive, but due to storage limitations, we can only provide the source data. Users can render it themselves. Thanks for you question. This week I will find a way to upload all the data to the appropriate cloud so you can download it.

**Comment by OolongQian** [comment]
Thank you for your kind reply! I will try to use source data, dataset/render_tools and dataset/process_tools to produce the input data.

**Comment by OolongQian** [comment]
Just in case of ambiguity, what I meant in the last reply is that, I will try to produce the input data for temporary use. And I am looking forward to your kind data release this week.
